### PR TITLE
Support TLS with optional CA validation

### PR DESCRIPTION
**Pull request by Matthew-Beckett**
Fixes/Implement: TLS support for MQTT endoints

**Description:**

This PR will allow you to connect to TLS secured MQTT endpoints. It also allows you to disable verification of the server's certificate if it is not signed by an trusted CA.

**Before the commit:**

```
mqtt-exporter_1  | Traceback (most recent call last):
mqtt-exporter_1  |   File "/opt/mqtt-exporter/exporter.py", line 5, in <module>
mqtt-exporter_1  |     main()
mqtt-exporter_1  |   File "/opt/mqtt-exporter/mqtt_exporter/main.py", line 353, in main
mqtt-exporter_1  |     client.connect(settings.MQTT_ADDRESS, settings.MQTT_PORT, settings.MQTT_KEEPALIVE)
mqtt-exporter_1  |   File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 914, in connect
mqtt-exporter_1  |     return self.reconnect()
mqtt-exporter_1  |   File "/usr/local/lib/python3.10/site-packages/paho/mqtt/client.py", line 1073, in reconnect
mqtt-exporter_1  |     sock.do_handshake()
mqtt-exporter_1  |   File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
mqtt-exporter_1  |     self._sslobj.do_handshake()
mqtt-exporter_1  | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1007)
```

**After the commit:**

```
DEBUG:mqtt-exporter:Enabling TLS on MQTT client
DEBUG:mqtt-exporter:Not verifying MQTT certificate authority is trusted
DEBUG:mqtt-exporter:Sending CONNECT (u1, p1, wr0, wq0, wf0, c1, k60) client_id=b''
DEBUG:mqtt-exporter:Received CONNACK (0, 0)
INFO:mqtt-exporter:subscribing to "<REDACTED>"
DEBUG:mqtt-exporter:Sending SUBSCRIBE (d0, m1) [(b'<REDACTED>', 0)]
DEBUG:mqtt-exporter:Received SUBACK
```

### CODE REVIEW

**Comment by kpetremann** [comment]
Hello @Matthew-Beckett,

Nice, thanks for this contribution!
Could you please just fix the error reported by the CI? I'll merge it once good.

**Comment by Matthew-Beckett** [comment]
@kpetremann can you offer some insight into how they imports are failing the tests?

**Comment by kpetremann** [comment]
hello @Matthew-Beckett,
was my last message helpful?

**Comment by Matthew-Beckett** [comment]
> 

Yes, sorry, just been very busy. Will resolve this ASAP.

**Comment by kpetremann** [comment]
Hi @Matthew-Beckett,

I am closing this PR as I created a replica with needed rebase and fixes - including your commit with you as author :)

see #75

**Pull request closed without merging**
